### ISSUE TITLE
functools32 not found when executing run-api

### ISSUE THREAD

**Issue by gomezgoiri** [PTAnywhere/pt-instances-management#2]
```
[user@host ~]$ /data/user-data/agg96/ptapi/bin/run-api -createdb -config /data/user-data/agg96/config.ini
Traceback (most recent call last):
File "/data/user-data/agg96/ptapi/bin/run-api", line 5, in
from pkg_resources import load_entry_point
File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 3007, in
working_set.require(requires)
File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
needed = self.resolve(parse_requirements(requirements))
File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: functools32
```

**Comment by gomezgoiri** [comment]
Quick (temporary) solution:
`[user@host ~]]$ /data/user-data/agg96/ptapi/bin/pip install functools32`

**Comment by gomezgoiri** [comment]
Issue moved from https://github.com/PTAnywhere/ptAnywhere-installation/issues/2

**Comment by gomezgoiri** [comment]
Ugly fix, I should get back to this in the future.

**Comment by gomezgoiri** [comment]
To solve issue #3 I started using jsonschema's version 2.4.0, which caused another conflict (with _easy\_install_?) when using _run-api_ command:
```
[agg96@kmi-appsvr05 ~]$ /data/user-data/agg96/ptapi/bin/run-api -createdb -config /data/user-data/agg96/config.ini
Traceback (most recent call last):
  File "/data/user-data/agg96/ptapi/bin/run-api", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (jsonschema 2.4.0 (/data/user-data/agg96/ptapi/lib/python2.7/site-packages), Requirement.parse('jsonschema>=2.5.1'))
```

**Comment by gomezgoiri** [comment]
While the related bug is solved, I have changed the way in which databases are created in the [installation scripts](https://github.com/PTAnywhere/ptAnywhere-installation/issues/2).

**Comment by gomezgoiri** [comment]
I close it as the new problem why I reopened this issue was not exactly the same.

The new issue has been described in #4.
