### ISSUE TITLE
jsonschema version conflict when using run-api command

### ISSUE THREAD

**Issue by gomezgoiri** [PTAnywhere/pt-instances-management#4]
To solve issue #3 I started using jsonschema's version 2.4.0, which caused another conflict (with _easy_install_?) when using _run-api_ command:

```
$ ptapi/bin/run-api -createdb -config config.ini
Traceback (most recent call last):
  File "/data/user-data/agg96/ptapi/bin/run-api", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (jsonschema 2.4.0 (/data/user-data/agg96/ptapi/lib/python2.7/site-packages), Requirement.parse('jsonschema>=2.5.1'))
```

**Comment by gomezgoiri** [comment]
Quick ugly fix (while the version 2.4.0 problem is solved).

Use `python ptapi/src/ptinstancemanager/src/ptinstancemanager/run.py` instead of `run-api`.
